### ISSUE TITLE
issue regarding locstats

### ISSUE THREAD

**Issue by Kanakalasriharika** [kokkonisd/locstats#17]
after installing locstats library using pip install locstats  it is not running i am getting an error like this
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_4720\1885956530.py in <module>
----> 1 loc_stats[loc_stats<=10]

NameError: name 'loc_stats' is not defined

**Comment by kokkonisd** [comment]
Hi!

Can you provide more information about your setup?
Which command did you run that lead to this error being produced?

I'm a bit surprised by what you mentioned since I can't find the string `loc_stats` anywhere in the source code, let alone the entire line that you attached. Are you sure that line is not part of some other code outside locstats?

**Comment by Kanakalasriharika** [comment]
[image: image.png]
this command

**Comment by Kanakalasriharika** [comment]
[image: image.png]

**Comment by Kanakalasriharika** [comment]
can you say me how to use this command??

**Comment by kokkonisd** [comment]
Well that highly depends on what you want to do.

Using locstats as a command-line tool is very well explained in the [README](https://github.com/kokkonisd/locstats/blob/master/README.md#using-locstats):
```console
$ locstats c ~/code/C/ --strict
You have written approximately 28807 LOC in C.
```

Using it as a library (i.e. writing code that calls locstats' API) is not as well documented currently, but you can pretty much copy [what `__main__.py` does](https://github.com/kokkonisd/locstats/blob/master/src/locstats/__main__.py#L74-L102).
